import SkeletonCustomProduct from "@/components/skeleton/pages/customProductPage";
import { useDispatch } from "@/redux/store";
import CustomProductSection from "@/sections/customProduct";
import { apiSSGV2DataService } from "@/utils/apiSSGV2DataService";
import { LayoutData } from "@/utils/layout";
import { setClientSideReduxCookie } from "@/utils/serverSideAction";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const WebLayout = dynamic(() => import("@/layouts/web"), {
  loading: () => <SkeletonCustomProduct />,
  ssr: false,
});

export const getStaticProps = async (context) => {
  const { locale } = context;
  const [customProductLayout, customProductPageData] = await Promise.all([
    LayoutData({
      param: {
        page_name: "the-met",
      },
      locale: locale,
    }),
    apiSSGV2DataService.getAll(`v2/homepage/first`, {
      content: "custom_product",
      locale,
    }),
  ]);
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"], null, ["en", "no"])),
      customProductLayout: customProductLayout,
      customProductPageData: customProductPageData?.data,
      revalidate:
        parseInt(process.env.NEXT_PUBLIC_COOKIE_MAX_AGE_ONE_WEEK) || 3600,
    },
  };
};

export default function TheMet(props) {
  const { customProductLayout, customProductPageData } = props;
  const dispatch = useDispatch();
  const router = useRouter();

  const layout = {
    HEADER: {
      TOPBAR: customProductLayout?.result?.HEADER?.SG_TOP_BAR || [],
      MIDMENU: customProductLayout?.result?.HEADER?.SGMIDSEC || [],
      CATEGORIES: customProductLayout?.result?.HEADER?.SGMEGAMENU || [],
      LOGO: customProductLayout?.result?.HEADER?.LOGO || null,
    },
    FOOTER: {
      firstSection: customProductLayout?.result?.FOOTER?.SG_FOOTER_1 || [],
      secondSection: customProductLayout?.result?.FOOTER?.SG_FOOTER_2 || [],
      thirdSection: customProductLayout?.result?.FOOTER?.SG_FOOTER_3 || [],
      fourthSection: customProductLayout?.result?.FOOTER?.SG_FOOTER_4 || [],
    },
    SEO: customProductLayout?.result?.SEO,
  };

  React.useEffect(() => {
    setClientSideReduxCookie({ dispatch: dispatch, router: router });
  }, [router]);
  return (
    <React.Fragment>
      <Head>
        <title>Sedar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebLayout layout={layout}>
        <CustomProductSection customProductPageData={customProductPageData} />
      </WebLayout>
    </React.Fragment>
  );
}
